version: '3.5'

services:
  pg-zetta:
    container_name: pg-zetta
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dbzetta